# Generated by Django 4.1.3 on 2023-01-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=200)),
                ('demand1', models.IntegerField()),
                ('demand2', models.IntegerField()),
                ('demand3', models.IntegerField()),
                ('demand4', models.IntegerField()),
                ('numPermanent', models.IntegerField()),
                ('prodPermanent', models.IntegerField()),
                ('prodTemporary', models.IntegerField()),
                ('costHiring', models.DecimalField(decimal_places=2, max_digits=19)),
                ('costFiring', models.DecimalField(decimal_places=2, max_digits=19)),
                ('costHoldingUnit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('inventoryInitial', models.IntegerField()),
                ('inventoryFinal', models.IntegerField()),
                ('inventoryMonth1', models.IntegerField()),
                ('inventoryMonth2', models.IntegerField()),
                ('inventoryMonth3', models.IntegerField()),
                ('hiredTemporary1', models.IntegerField()),
                ('hiredTemporary2', models.IntegerField()),
                ('hiredTemporary3', models.IntegerField()),
                ('hiredTemporary4', models.IntegerField()),
                ('firedTemporary1', models.IntegerField()),
                ('firedTemporary2', models.IntegerField()),
                ('firedTemporary3', models.IntegerField()),
                ('firedTemporary4', models.IntegerField()),
                ('optimalCost', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
