# Generated by Django 4.1.3 on 2023-01-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costFiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costFiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costFiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costFiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costFiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costFiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costFiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costFiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHoldingUnit1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHoldingUnit2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHoldingUnit3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHoldingUnit4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHoldingUnit5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHoldingUnit6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHoldingUnit7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='costHoldingUnit8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodPermanent1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodPermanent2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodPermanent3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodPermanent4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodPermanent5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodPermanent6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodPermanent7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodPermanent8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodTemporary1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodTemporary2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodTemporary3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodTemporary4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodTemporary5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodTemporary6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodTemporary7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eightmonthplan',
            name='prodTemporary8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring11',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costFiring9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring11',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHiring9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit11',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='costHoldingUnit9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent10',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent11',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodPermanent9',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary10',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary11',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='elevenmonthplan',
            name='prodTemporary9',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costFiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costFiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costFiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costFiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costFiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHoldingUnit1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHoldingUnit2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHoldingUnit3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHoldingUnit4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='costHoldingUnit5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodPermanent1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodPermanent2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodPermanent3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodPermanent4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodPermanent5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodTemporary1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodTemporary2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodTemporary3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodTemporary4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fivemonthplan',
            name='prodTemporary5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costFiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costFiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costFiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costFiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costHiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costHiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costHiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costHiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costHoldingUnit1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costHoldingUnit2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costHoldingUnit3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='costHoldingUnit4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='prodPermanent1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='prodPermanent2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='prodPermanent3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='prodPermanent4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='prodTemporary1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='prodTemporary2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='prodTemporary3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fourmonthplan',
            name='prodTemporary4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costFiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costFiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costFiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costFiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costFiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costFiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costFiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costFiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costFiring9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHiring9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHoldingUnit1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHoldingUnit2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHoldingUnit3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHoldingUnit4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHoldingUnit5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHoldingUnit6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHoldingUnit7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHoldingUnit8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='costHoldingUnit9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodPermanent1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodPermanent2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodPermanent3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodPermanent4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodPermanent5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodPermanent6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodPermanent7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodPermanent8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodPermanent9',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodTemporary1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodTemporary2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodTemporary3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodTemporary4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodTemporary5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodTemporary6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodTemporary7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodTemporary8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ninemonthplan',
            name='prodTemporary9',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costFiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costFiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costFiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costFiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costFiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costFiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costFiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHoldingUnit1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHoldingUnit2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHoldingUnit3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHoldingUnit4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHoldingUnit5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHoldingUnit6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='costHoldingUnit7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodPermanent1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodPermanent2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodPermanent3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodPermanent4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodPermanent5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodPermanent6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodPermanent7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodTemporary1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodTemporary2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodTemporary3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodTemporary4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodTemporary5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodTemporary6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sevenmonthplan',
            name='prodTemporary7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costFiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costFiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costFiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costFiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costFiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costFiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHoldingUnit1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHoldingUnit2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHoldingUnit3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHoldingUnit4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHoldingUnit5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='costHoldingUnit6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodPermanent1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodPermanent2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodPermanent3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodPermanent4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodPermanent5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodPermanent6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodTemporary1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodTemporary2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodTemporary3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodTemporary4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodTemporary5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sixmonthplan',
            name='prodTemporary6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costFiring9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHiring9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='costHoldingUnit9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent10',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodPermanent9',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary10',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tenmonthplan',
            name='prodTemporary9',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring11',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring12',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costFiring9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring11',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring12',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHiring9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit10',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit11',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit12',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit3',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit4',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit5',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit6',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit7',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit8',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='costHoldingUnit9',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent10',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent11',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent12',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodPermanent9',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary10',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary11',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary12',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary6',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary7',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary8',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='twelvemonthplan',
            name='prodTemporary9',
            field=models.IntegerField(default=1),
        ),
    ]
