# Generated by Django 4.1.3 on 2022-12-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_workerextra_bossextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('productionTempWorker', models.IntegerField()),
                ('monthlyInventoryConstraints', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NTWDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempWorkerMonthly', models.IntegerField(default=0)),
            ],
        ),
    ]
