# Generated by Django 4.1.3 on 2023-01-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plandatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandatabase',
            name='firedTemporary1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='firedTemporary2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='firedTemporary3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='firedTemporary4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='hiredTemporary1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='hiredTemporary2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='hiredTemporary3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='hiredTemporary4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='inventoryMonth1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='inventoryMonth2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='inventoryMonth3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plandatabase',
            name='optimalCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
