# Generated by Django 4.1.3 on 2022-12-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_icdatabase_ntwdatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ntwdatabase',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ntwdatabase',
            name='tempWorkerMonthly',
            field=models.IntegerField(null=True),
        ),
    ]
